title = "Enzo's zenzone"
theme = "apollo"
taxonomies = [{ name = "tags" }]

# The URL the site will be built for
base_url = "https://enzo.cranford.fr"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
theme = "toggle"
menu = [
    { name = "/projects", url = "/projects", weight = 2 },
    { name = "/about", url = "/about", weight = 3 },
]
socials = [
    { name = "mastodon", url = "https://mastodon.social/@enzoritto", icon = "mastodon" },
    { name = "github", url = "https://github.com/enzoritto/", icon = "github" },
]

repo_view = true
repo_url = "https://github.com/enzoritto/enzo.cranford.fr"
